# Generated by Django 5.2.7 on 2025-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FD", "0002_alter_invoice_balance_due_alter_invoice_invoice_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workorder",
            name="is_migrated",
            field=models.BooleanField(default=False),
        ),
    ]
