# Generated by Django 5.2.7 on 2025-10-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FD", "0003_customer_is_migrated_invoice_is_migrated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfiguration",
            name="email_subject",
            field=models.CharField(
                default="Payment Reminder: Invoice {invoice_number}", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="emailconfiguration",
            name="email_template",
            field=models.TextField(
                default="Dear {customer_name},\n\nThis is a friendly reminder that your invoice is pending payment.\n\nInvoice Number: {invoice_number}\nTotal Amount: ₹{total_amount}\nBalance Due: ₹{balance_due}\nProject: {project_title}\nDue Date: {due_date}\n\nPlease make the payment at your earliest convenience.\n\nBest regards,\nFolkDrive Team"
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="days_after_invoice",
            field=models.IntegerField(
                default=7,
                help_text="Days after invoice creation to send first reminder",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="name",
            field=models.CharField(default="Default", max_length=255),
        ),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="reminder_frequency",
            field=models.IntegerField(
                default=3, help_text="Frequency in days between reminders"
            ),
        ),
    ]
