# Generated by Django 5.2.7 on 2025-10-18 06:07

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FD", "0005_workorder_base_amount_workorder_discount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="FolkDrive", max_length=255)),
                (
                    "legal_name",
                    models.CharField(default="FolkDrive Solutions", max_length=255),
                ),
                ("address", models.TextField(default="Your Company Address")),
                ("city", models.CharField(default="City", max_length=100)),
                ("state", models.CharField(default="Gujarat", max_length=100)),
                ("pincode", models.CharField(default="380001", max_length=10)),
                ("phone", models.CharField(default="+91-XXXXXXXXXX", max_length=15)),
                (
                    "email",
                    models.EmailField(default="info@folkdrive.com", max_length=254),
                ),
                ("website", models.URLField(default="https://folkdrive.com")),
                (
                    "gst_number",
                    models.CharField(default="GSTINXXXXXXXXXXXXX", max_length=15),
                ),
                ("pan_number", models.CharField(default="XXXXXXXXXX", max_length=10)),
                ("state_code", models.CharField(default="24", max_length=2)),
                ("bank_name", models.CharField(default="Bank Name", max_length=255)),
                (
                    "account_number",
                    models.CharField(default="XXXXXXXXXXXX", max_length=20),
                ),
                (
                    "account_holder",
                    models.CharField(default="FolkDrive Solutions", max_length=255),
                ),
                ("ifsc_code", models.CharField(default="XXXX0000000", max_length=11)),
                ("branch", models.CharField(default="Branch Name", max_length=100)),
                (
                    "invoice_terms",
                    models.TextField(
                        default="Payment due within 30 days of invoice date."
                    ),
                ),
                (
                    "invoice_footer",
                    models.TextField(default="Thank you for your business!"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Company Settings",
                "db_table": "fd_company_settings",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-payment_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="invoice",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cgst_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cgst_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("9.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="hsn_code",
            field=models.CharField(blank=True, default="998314", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="igst_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="igst_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_service",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_collected_at_conversion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="place_of_supply",
            field=models.CharField(blank=True, default="Gujarat", max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sac_code",
            field=models.CharField(blank=True, default="998314", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sgst_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("9.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="hsn_code",
            field=models.CharField(blank=True, default="998314", max_length=10),
        ),
        migrations.AddField(
            model_name="workorder",
            name="is_service",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="place_of_supply",
            field=models.CharField(blank=True, default="Gujarat", max_length=100),
        ),
        migrations.AddField(
            model_name="workorder",
            name="sac_code",
            field=models.CharField(blank=True, default="998314", max_length=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="work_order_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
