# Generated by Django 5.2.7 on 2025-10-18 13:53

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FD", "0006_companysettings_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "db_table": "fd_project_category",
            },
        ),
        migrations.CreateModel(
            name="TaxConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="GST", max_length=100)),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("9.00"), max_digits=5
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("9.00"), max_digits=5
                    ),
                ),
                (
                    "igst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18.00"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Tax Configuration",
                "verbose_name_plural": "Tax Configurations",
                "db_table": "fd_tax_configuration",
            },
        ),
        migrations.AlterModelOptions(
            name="companysettings",
            options={
                "verbose_name": "Company Setting",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="emailconfiguration",
            options={
                "verbose_name": "Email Configuration",
                "verbose_name_plural": "Email Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="emaillog",
            options={"verbose_name": "Email Log", "verbose_name_plural": "Email Logs"},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "Invoice", "verbose_name_plural": "Invoices"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payment_date", "-created_at"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentreminderlog",
            options={
                "verbose_name": "Payment Reminder Log",
                "verbose_name_plural": "Payment Reminder Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="termsandconditions",
            options={
                "verbose_name": "Terms and Conditions",
                "verbose_name_plural": "Terms and Conditions",
            },
        ),
        migrations.AlterModelOptions(
            name="workorder",
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
            },
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="tax_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="gst_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
