# Generated by Django 5.2.7 on 2025-10-19 03:29

import FD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FD", "0007_projectcategory_taxconfiguration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gst_number",
            field=models.CharField(
                max_length=15, unique=True, validators=[FD.models.validate_gst_number]
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile_number",
            field=models.CharField(
                max_length=15, validators=[FD.models.validate_mobile_number]
            ),
        ),
    ]
